project/project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('authorization.urls', namespace='auth')),
    url(r'^main/', include('tasks.urls', namespace='tasks')),
    url(r'^profile/', include('profiles.urls', namespace='profile')),
    url(r'^$', RedirectView.as_view(
            pattern_name='tasks:list', permanent=False)),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

project/tasks/urls.py
from django.conf.urls import url

from .views import (TaskListView, TaskCreateView,
                    TaskDetailView, FileCreateView,
                    ExpectDateUpdateView, ResolveTaskUpdateView,
                    AcceptTaskPerformanceUpdateView, GetCsvView)

urlpatterns = [
    url(r'^$', TaskListView.as_view(), name='list'),
    url(r'^create/$', TaskCreateView.as_view(), name='create'),
    url(r'^file_create/$', FileCreateView.as_view(), name='file_create'),
    url(r'^get_csv/$', GetCsvView.as_view(), name='get_csv'),
    url(r'^(?P<slug>[\w-]+)/$', TaskDetailView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/expect_date_change/$',
        ExpectDateUpdateView.as_view(), name='expect_date_change'),
    url(r'^(?P<slug>[\w-]+)/resolve/$',
        ResolveTaskUpdateView.as_view(), name='resolve_task'),
    url(r'^(?P<slug>[\w-]+)/accept/$',
        AcceptTaskPerformanceUpdateView.as_view(), name='accept_task'),
]

project/tasks/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
# from django.db.models.signals import pre_save
# from django.utils.text import slugify
# from django.utils.translation import ugettext_lazy as _


class Status(models.Model):
    """docstring for Status"""
    name = models.CharField(max_length=64)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Statuses'


class Task(models.Model):

    '''
        Slug create from title ??????????
    '''

    author = models.ForeignKey(User, related_name='author')
    title = models.CharField(max_length=128)
    description = models.TextField()
    start_date = models.DateTimeField(auto_now_add=True, auto_now=False)
    expect_date = models.DateField(null=True, blank=True)
    end_date = models.DateTimeField(null=True, blank=True)
    status = models.ForeignKey(Status, default=1, related_name='status')
    expert = models.ForeignKey(User, related_name='expert')
    slug = models.SlugField(max_length=224, unique=True)

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['-pk']


class Comment(models.Model):
    author = models.ForeignKey(User)
    text = models.TextField()
    is_watch = models.BooleanField(default=False)
    create_date = models.DateTimeField(auto_now_add=True, auto_now=False)
    tasks = models.ForeignKey(Task)

    def __unicode__(self):
        return '%s...' % (self.text[:20])

    class Meta:
        ordering = ['create_date']


def content_file_name(instance, filename):
    return '/'.join(['files', instance.tasks.slug, filename])


class File(models.Model):
    file = models.FileField(upload_to=content_file_name)
    create_date = models.DateTimeField(auto_now_add=True, auto_now=False)
    author = models.ForeignKey(User)
    tasks = models.ForeignKey(Task)

    def __unicode__(self):
        return self.file.name

    class Meta:
        ordering = ['create_date']

project/tasks/forms.py
import datetime

from django import forms
from django.conf import settings
from django.core.validators import ValidationError
from django.template.defaultfilters import filesizeformat
from django.utils.translation import ugettext_lazy as _

from crispy_forms.bootstrap import StrictButton
from crispy_forms.layout import Layout, ButtonHolder, Submit
from crispy_forms.helper import FormHelper

from .models import Task, Comment, File


class CSVForm(forms.Form):
    date_from = forms.DateField()
    date_to = forms.DateField()

    def __init__(self, *args, **kwargs):
        super(CSVForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.html5_required = True
        self.helper.form_tag = False
        self.helper.field_template = 'bootstrap3/layout/inline_field.html'
        self.helper.layout = Layout(
            'date_from',
            'date_to',
            StrictButton('Get CSV', type='submit', css_class='btn-default'),
        )

    def clean(self):
        cleaned_data = super(CSVForm, self).clean()
        date_from = cleaned_data.get('date_from')
        date_to = cleaned_data.get('date_to')
        if date_from > date_to:
            raise ValidationError(_('Date to must be in future'),
                                  code=_('invalid'))


class TaskForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(TaskForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.html5_required = True
        self.helper.form_show_errors = True
        self.helper.layout = Layout(
            'title',
            'description',
            ButtonHolder(
                Submit('submit', 'Submit', css_class='button')
            )
        )

    class Meta:
        model = Task
        fields = ['title', 'description']


class ExpectDateForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ['expect_date', ]

    def clean_expect_date(self):
        expect_date = self.cleaned_data.get('expect_date')

        if expect_date:
            if expect_date < datetime.date.today():
                raise forms.ValidationError(_('Expect Date must be in future'),
                                            code=_('invalid'))
        else:
            raise forms.ValidationError(_('Expect Date empty'),
                                        code=_('invalid'))
        return expect_date


class FileForm(forms.ModelForm):

    class Meta:
        model = File
        fields = ['file', ]

    def clean_file(self):
        file = self.cleaned_data.get('file')

        if file:
            if len(file.name.split('.')) == 1:
                raise forms.ValidationError(_('File type is not supported'),
                                            code=_('invalid'))

            if file.content_type in settings.TASK_UPLOAD_FILE_TYPES:
                if file._size > settings.TASK_UPLOAD_FILE_MAX_SIZE:
                    raise forms.ValidationError(
                        _('Please keep filesize under %s. Current filesize %s')
                        % (filesizeformat(
                            settings.TASK_UPLOAD_FILE_MAX_SIZE),
                            filesizeformat(file._size)), code=_('invalid'))
            else:
                raise forms.ValidationError(_('File type is not supported'),
                                            code=_('invalid'))

        return file


class CommentForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.html5_required = True
        self.helper.form_show_errors = True
        self.helper.form_show_labels = False
        self.helper.form_tag = False
        self.helper.layout = Layout(
            'text'
        )

    class Meta:
        model = Comment
        fields = ['text', ]
        widgets = {
            'text': forms.Textarea(attrs={
                'rows': 4, 'placeholder': _('Type the comment...')}),
        }

project/tasks/views.py
import csv
import datetime
import logging

from django.views.generic import ListView, FormView, TemplateView, UpdateView
from django.core.urlresolvers import reverse_lazy, reverse
from django.contrib.auth.mixins import (
    LoginRequiredMixin, PermissionRequiredMixin)
from django.shortcuts import get_object_or_404, redirect
from django.http import Http404, HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils.translation import ugettext_lazy as _
from django.contrib import messages
from django.utils.encoding import smart_str

from .models import Task
from .forms import TaskForm, CommentForm, FileForm, ExpectDateForm, CSVForm
from generic.functions.create_log_for_superuser import prepare_and_create_log


logger = logging.getLogger(__name__)


class TaskListView(LoginRequiredMixin, ListView):
    template_name = 'tasks/list.html'
    login_url = reverse_lazy('auth:login')

    def get_queryset(self, *args, **kwargs):
        if self.request.user.groups.filter(pk=2).exists():
            return Task.objects.filter(expert=self.request.user)
        elif self.request.user.groups.filter(pk=3).exists():
            return Task.objects.all()
        elif self.request.user.groups.filter(pk=1).exists():
            return Task.objects.filter(author=self.request.user)
        else:
            raise Http404

    def get_context_data(self, **kwargs):
        context = super(TaskListView, self).get_context_data(**kwargs)

        if self.request.user.groups.filter(name='super').exists():
            if context['object_list']:
                context['can_get_csv'] = True
                context['form_csv'] = CSVForm(self.request.POST or None)

        context['task'] = {
            'pending': [],
            'in_proccess': [],
            'closed': [],
            'other': [],
        }

        for obj in context['object_list']:
            if obj.status.name == 'pending':
                context['task']['pending'].append(obj)
            elif obj.status.name == 'in process':
                context['task']['in_proccess'].append(obj)
            elif obj.status.name == 'closed':
                context['task']['closed'].append(obj)
            else:
                context['task']['other'].append(obj)

        return context


class TaskCreateView(PermissionRequiredMixin, FormView):
    form_class = TaskForm
    template_name = 'tasks/form_task.html'
    success_url = reverse_lazy('tasks:list')

    permission_required = 'tasks.add_task'
    raise_exception = True
    login_url = reverse_lazy('auth:login')

    def form_valid(self, form, *args, **kwargs):
        new_task = form.save(commit=False)
        new_task.author = self.request.user
        new_task.expert_id = 3
        new_task.save()
        # send_mail(
        #     'Subject here',
        #     'Here is the message.',
        #     settings.EMAIL_HOST_USER,
        #     ['kvorobiov89@gmail.com'],
        #     fail_silently=False
        # )

        prepare_and_create_log(
            1,
            new_task.author.profile.slug,
            new_task.slug,
            ''
        )
        logger.error(_("User expires date less than now"))
        messages.success(self.request, _('Task successfully created!'))

        return super(TaskCreateView, self).form_valid(form)


class TaskDetailView(LoginRequiredMixin, TemplateView):

    template_name = 'tasks/detail.html'
    paginate_by = 5

    login_url = reverse_lazy('auth:login')

    def dispatch(self, request, *args, **kwargs):
        slug = kwargs.get('slug')
        obj = get_object_or_404(Task, slug=slug)
        if self.request.user not in [obj.expert, obj.author]:
            if not request.user.groups.filter(name='super').exists():
                raise Http404

        return super(TaskDetailView, self).dispatch(
            request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        slug = kwargs.pop('slug')
        context = super(TaskDetailView, self).get_context_data(**kwargs)
        context['object'] = get_object_or_404(Task, slug=slug)

        if context['object'].status.id == 1 and \
                context['object'].expert == self.request.user:
            if not context['object'].expect_date:
                context['must_setup_expect_date'] = True

        if context['object'].status.id in [3, 6] and \
                context['object'].expert == self.request.user:
            context['must_resolved'] = True

        if context['object'].status.id == 4 and \
                context['object'].author == self.request.user:
            context['must_accept_task'] = True

        context['form_comment'] = CommentForm(self.request.POST or None)
        context['form_file'] = FileForm()
        context['form_expect_date'] = ExpectDateForm()

        comments = context['object'].comment_set.all()
        paginator = Paginator(comments, self.paginate_by)
        page = self.request.GET.get('page')
        try:
            context['comments'] = paginator.page(page)
        except PageNotAnInteger:
            context['comments'] = paginator.page(1)
        except EmptyPage:
            context['comments'] = paginator.page(paginator.num_pages)

        return context

    def post(self, request, slug, *args, **kwargs):
        form = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.author = request.user
            new_comment.tasks = get_object_or_404(Task, slug=slug)
            new_comment.save()

            prepare_and_create_log(
                2,
                new_comment.author.profile.slug,
                new_comment.tasks.slug,
                2
            )

            messages.success(self.request, _('Comment successfully added!'))
        else:
            return self.render_to_response(self.get_context_data(slug=slug))
        return redirect(reverse('tasks:detail', kwargs={'slug': slug}))


class FileCreateView(LoginRequiredMixin, FormView):
    form_class = FileForm
    login_url = reverse_lazy('auth:login')

    def dispatch(self, *args, **kwargs):
        self.refer = self.request.META.get('HTTP_REFERER', '/')
        if self.refer == '/':
            raise Http404
        return super(FileCreateView, self).dispatch(*args, **kwargs)

    def form_valid(self, form, *args, **kwargs):
        new_file = form.save(commit=False)
        new_file.author = self.request.user
        # !!!
        slug = self.refer.split('/')[-2]
        new_file.tasks = get_object_or_404(Task, slug=slug)
        new_file.save()

        prepare_and_create_log(
            2,
            new_file.author.profile.slug,
            new_file.tasks.slug,
            4
        )
        messages.success(self.request, _('File successfully added!'))
        return redirect(self.refer)

    def form_invalid(self, form, *args, **kwargs):
        return redirect(self.refer)


class ExpectDateUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    form_class = ExpectDateForm
    login_url = reverse_lazy('auth:login')

    def dispatch(self, *args, **kwargs):
        self.refer = self.request.META.get('HTTP_REFERER', '/')
        if self.refer == '/':
            raise Http404
        if not self.request.user.groups.filter(name='experts').exists():
            raise Http404
        return super(ExpectDateUpdateView, self).dispatch(*args, **kwargs)

    def form_valid(self, form, *args, **kwargs):
        expect_date = form.save(commit=False)
        expect_date.status_id = 3
        expect_date.save()
        messages.success(self.request, _('Expect date successfully added!'))
        return redirect(self.refer)

    def form_invalid(self, form, *args, **kwargs):
        return redirect(self.refer)


class ResolveTaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ['title', ]
    login_url = reverse_lazy('auth:login')

    def dispatch(self, *args, **kwargs):
        self.refer = self.request.META.get('HTTP_REFERER', '/')
        if self.refer == '/':
            raise Http404
        if not self.request.user.groups.filter(name='experts').exists():
            raise Http404
        return super(ResolveTaskUpdateView, self).dispatch(*args, **kwargs)

    def post(self, *args, **kwargs):
        if self.request.POST.get('resolved_task'):
            object = self.get_object()
            if object.status_id in [3, 6]:
                object.status_id = 4
                object.save()
                messages.success(
                    self.request, _('Status successfully changed!'))
        return redirect(self.refer)


class AcceptTaskPerformanceUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ['title', ]
    login_url = reverse_lazy('auth:login')

    def dispatch(self, *args, **kwargs):
        self.refer = self.request.META.get('HTTP_REFERER', '/')
        if self.refer == '/':
            raise Http404
        if not self.request.user.groups.filter(name='customers').exists():
            raise Http404
        return super(AcceptTaskPerformanceUpdateView, self).dispatch(
            *args, **kwargs)

    def post(self, *args, **kwargs):
        object = self.get_object()
        if object.status_id == 4:
            if self.request.POST.get('accept_task'):
                object.status_id = 5
                object.end_date = datetime.datetime.now()
                object.save()

                prepare_and_create_log(
                    3,
                    object.author.profile.slug,
                    object.slug,
                    ''
                )
            if self.request.POST.get('reopen_task'):
                object.status_id = 6
                object.save()
            messages.success(self.request, _('Status successfully changed!'))

        return redirect(self.refer)


class GetCsvView(LoginRequiredMixin, FormView):
    form_class = CSVForm

project/tasks/templates/tasks/detail.html
{% extends "tasks_base.html" %}
{% load crispy_forms_tags %}

{% block app_content %}
    <div class="row">
        <h1 class="col-sm-8">
            <span class="label label-stat_{{ object.status.pk }}"><span class="label-content">{{ object.status }}</span></span> {{ object.title|upper }}
            <small>by {{ object.author|title }}</small>
        </h1>
    </div>
        {% if must_setup_expect_date %}
            <br>
            <hr>
            <div class="panel panel-warning">
                <div class="panel-heading">Please setup expect date!</div>
                <div class="panel-body">
                    <form class="form-inline" method="POST" action="{% url 'tasks:expect_date_change' object.slug %}">
                    {% csrf_token %}
                        {{ form_expect_date }}
                        <button type="submit" class="btn btn-default">Send date</button>
                    </form>
                </div>
            </div>
        {% endif %}
        {% if must_resolved %}
            <br>
            <hr>
            <div class="panel panel-info">
                <div class="panel-heading">Please click if you resolved tasks!</div>
                <div class="panel-body">
                    <form class="form-inline" method="POST" action="{% url 'tasks:resolve_task' object.slug %}">
                    {% csrf_token %}
                        <button type="submit" name='resolved_task' value='1' class="btn btn-default">Resolve</button>
                    </form>
                </div>
            </div>
        {% endif %}
        {% if must_accept_task %}
            <br>
            <hr>
            <div class="panel panel-info">
                <div class="panel-heading">Please click 'Closed task' if expert done your task or click on 'Reopen task' if else</div>
                <div class="panel-body">
                    <form class="form-inline" method="POST" action="{% url 'tasks:accept_task' object.slug %}">
                    {% csrf_token %}
                        <button type="submit" name='accept_task' value='1' class="btn btn-success">Closed task</button>
                        <button type="submit" name='reopen_task' value='1' class="btn btn-danger">Reopen task</button>
                    </form>
                </div>
            </div>
        {% endif %}
    <br>
    <br>
    <h3>Description:</h3>
    <hr>
    <div class="well well-lg">{{ object.description }}</div>
    <br>
    <br>
    <h3>Detail tasks:</h3>
    <hr>
    <div>
        <p>Expert: <b>{{ object.expert|title }}</b></p>
        <p>Start date : <b>{{ object.start_date|default:'Uknown' }}</b></p>
        <p>Expect date : <b>{{ object.expect_date|default:'Uknown' }}</b></p>
        <p>Finish date : <b>{{ object.end_date|default:'Uknown' }}</b></p>
    </div>
    <br>
    <br>
    <h3>
        Attachments:
        <!-- Large modal -->
        {% ifnotequal object.status.id 5 %}
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-lg">+ Add file</button>
        {% endifnotequal %}
    </h3>
{% ifnotequal object.status.id 5 %}
<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="gridSystemModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        <form method="POST" action="{% url 'tasks:file_create' %}" enctype="multipart/form-data">
        {% csrf_token %}
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="gridSystemModalLabel">Add File</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        {{ form_file }}
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Save changes</button>
            </div>
        </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% endifnotequal %}
    <hr>
    <div>
        {% for f in object.file_set.all %}
            <p><a href="{{ f.file.url }}" target="blank">{{ f.file }}</a></p>
        {% empty %}
            <p>Files not find...</p>
        {% endfor %}
    </div>
    <br>
    <br>
    <h3>Comments:</h3>
    {% ifnotequal object.status.id 5 %}
    <form method="POST" action="{% url 'tasks:detail' object.slug %}">
        {% csrf_token %}
        {% crispy form_comment form_comment.helper %}
        <div class="control-group">
            <button type="submit" class="btn btn-success green">Leave Comment</button>
        </div>
    </form>
    {% endifnotequal %}
    <br>
    <br>
    <div>
    {% for comment in comments %}
        <div>
            <p><b>{{ comment.author|title }}:</b> <i>{{ comment.create_date }}</i></p>
            <!-- !!!!!!!!!!!!!!!!!!!! -->
            <p style="text-indent: 5%;">{{ comment.text }}</p>
            <br>
        </div>
    {% empty %}
        <p>No comments...</p>
    {% endfor %}
    </div>

    <div class="pagination">
        {% if comments.has_previous %}
            <li>
                <a href="{% url 'tasks:detail' object.slug %}?page={{ comments.previous_page_number }}">Prev</a>
            </li>
        {% endif %}
        {% for i in "x"|rjust:comments.paginator.num_pages %}
            {% if comments.paginator.num_pages > 1 %}
            <li {% if forloop.counter == comments.number %}class="active"{% endif %}>
                <a href="{% url 'tasks:detail' object.slug %}?page={{ forloop.counter }}">{{ forloop.counter }}</a>
            </li>
            {% endif %}
        {% endfor %}
        {% if comments.has_next %}
            <li>
                <a href="{% url 'tasks:detail' object.slug %}?page={{ comments.next_page_number }}">Next</a>
            </li>
        {% endif %}
    </div>

{% endblock app_content %}

project/tasks/templates/tasks/form_task.html
{% extends "tasks_base.html" %}
{% load crispy_forms_tags %}

{% block app_content %}
    <form method="POST" action="">
    {% csrf_token %}
        {% crispy form form.helper %}
    </form>
{% endblock app_content %}

project/tasks/templates/tasks/list.html
{% extends "tasks_base.html" %}
{% load crispy_forms_tags %}

{% block app_content %}
    {% comment %}
    <div class="row">
        <div class="col-md-12">
            <ul class="breadcrumb">
                <li>
                    <a href="#">Home</a>
                </li>
                <li class="active">Tour Leads</li>
            </ul>
        </div>
    </div>
    {% endcomment %}
    <div class="row">
        <div class="col-md-12">
            {% if can_get_csv %}
                <div>
                    <form class="form-inline" method="POST" action="{% url 'tasks:get_csv' %}">
                    {% csrf_token %}
                        {% crispy form_csv form_csv.helper %}
                    </form>
                </div>
            {% endif %}
            {% if perms.tasks.add_task %}
                <p><a href="{% url 'tasks:create' %}">Create new tasks</a></p>
            {% endif %}
            {% if task.pending %}
                <h3 class="text-center">Pending</h3>
                <br>
                <table class="table table-pending" id="table-sorted-pending">
                    <thead>
                        <tr class="active">
                            <th>Author</th>
                            <th>Title</th>
                            <th>Start date</th>
                            <th>Expect date</th>
                            <th>End date</th>
                            <th>Expert</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for object in task.pending %}
                        <tr>
                            <td>{{ object.author }}</td>
                            <td><a href="{% url 'tasks:detail' object.slug %}">{{ object.title }}</a></td>
                            <td>{{ object.start_date }}</td>
                            <td>{{ object.expect_date }}</td>
                            <td>{{ object.end_date }}</td>
                            <td>{{ object.expert }}</td>
                            <td>{{ object.status }}</td>
                        </tr>
                        {% empty %}
                            <tr>
                                <th colspan="8">
                                    <p class="text-center">Tasks is empty</p>
                                </th>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <hr>
            {% endif %}

            {% if task.in_proccess %}
                <h3 class="text-center">In Proccess</h3>
                <br>
                <table class="table table-in_proccess" id="table-sorted-in_proccess">
                    <thead>
                        <tr class="active">
                            <th>Author</th>
                            <th>Title</th>
                            <th>Start date</th>
                            <th>Expect date</th>
                            <th>End date</th>
                            <th>Expert</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for object in task.in_proccess %}
                        <tr>
                            <td>{{ object.author }}</td>
                            <td><a href="{% url 'tasks:detail' object.slug %}">{{ object.title }}</a></td>
                            <td>{{ object.start_date }}</td>
                            <td>{{ object.expect_date }}</td>
                            <td>{{ object.end_date }}</td>
                            <td>{{ object.expert }}</td>
                            <td>{{ object.status }}</td>
                        </tr>
                        {% empty %}
                            <tr>
                                <th colspan="8">
                                    <p class="text-center">Tasks is empty</p>
                                </th>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <hr>
            {% endif %}

            <h3 class="text-center">Tasks</h3>
            <br>
            <table class="table table-other" id="table-sorted-other">
                <thead>
                    <tr class="active">
                        <th>Author</th>
                        <th>Title</th>
                        <th>Start date</th>
                        <th>Expect date</th>
                        <th>End date</th>
                        <th>Expert</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for object in task.other %}
                    <tr>
                        <td>{{ object.author }}</td>
                        <td><a href="{% url 'tasks:detail' object.slug %}">{{ object.title }}</a></td>
                        <td>{{ object.start_date }}</td>
                        <td>{{ object.expect_date }}</td>
                        <td>{{ object.end_date }}</td>
                        <td>{{ object.expert }}</td>
                        <td>{{ object.status }}</td>
                    </tr>
                    {% empty %}
                        <tr>
                            <th colspan="8">
                                <p class="text-center">Tasks is empty</p>
                            </th>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>

            {% if task.closed %}
                <h3 class="text-center">Closed</h3>
                <br>
                <table class="table table-closed" id="table-sorted-closed">
                    <thead>
                        <tr class="active">
                            <th>Author</th>
                            <th>Title</th>
                            <th>Start date</th>
                            <th>Expect date</th>
                            <th>End date</th>
                            <th>Expert</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for object in task.closed %}
                        <tr>
                            <td>{{ object.author }}</td>
                            <td><a href="{% url 'tasks:detail' object.slug %}">{{ object.title }}</a></td>
                            <td>{{ object.start_date }}</td>
                            <td>{{ object.expect_date }}</td>
                            <td>{{ object.end_date }}</td>
                            <td>{{ object.expert }}</td>
                            <td>{{ object.status }}</td>
                        </tr>
                        {% empty %}
                            <tr>
                                <th colspan="8">
                                    <p class="text-center">Tasks is empty</p>
                                </th>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <hr>
            {% endif %}

        </div>
    </div>

{% endblock app_content %}